---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-cnpg
  namespace: keycloak
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  instances: 1
  storage:
    size: 5Gi
    storageClass: managed-csi-premium
  enableSuperuserAccess: true
  superuserSecret:
    name: keycloak-cnpg-superuser-creds
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-cnpg-creds
      import:
        type: microservice
        databases:
          - bitnami_keycloak
        source:
          externalCluster: keycloak-bitnami
  externalClusters:
    - name: keycloak-bitnami
      connectionParameters:
        host: keycloak-postgresql.keycloak.svc.cluster.local
        port: "5432"
        user: postgres
        dbname: postgres
      password:
        name: keycloak-external-creds
        key: password
