---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cloudagent-cnpg
  namespace: bob
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  instances: 2
  storage:
    size: 5Gi
    storageClass: managed-csi-premium
  enableSuperuserAccess: true
  superuserSecret:
    name: bob-cloudagent-cnpg-superuser-creds
  bootstrap:
    initdb:
      database: walletId
      owner: cloudagent
      secret:
        name: bob-cloudagent-cnpg-creds
      import:
        type: microservice
        databases:
          - walletId
        source:
          externalCluster: cloudagent-postgresql
  externalClusters:
    - name: cloudagent-postgresql
      connectionParameters:
        host: cloudagent-postgresql.bob.svc.cluster.local
        port: "5432"
        user: postgres
        dbname: postgres
      password:
        name: bob-cloudagent-cnpg-superuser-creds
        key: postgres-password
  enablePDB: false
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cloudagent-cnpg
  namespace: bob
spec:
  minAvailable: 1
  selector:
    matchLabels:
      cnpg.io/cluster: cloudagent-cnpg
