label: Charlie veritable-cloudagent REST API
endpoint: "http://cloudagent-veritable-cloudagent.charlie.svc.cluster.local:5002"
logLevel: trace
ingress:
  enabled: false
postgresql:
  enabled: false
externalDatabase:
  create: false
  host: cloudagent-cnpg-rw.charlie.svc.cluster.local
  port: 5432
  user: cloudagent
  database: walletId
  existingSecret: charlie-cloudagent-cnpg-creds
  existingSecretPasswordKey: password
  existingSecretPostgresPasswordKey: pgpass
ipfs:
  persistence:
    size: 5Gi
    storageClass: managed-csi-premium
  initConfig:
    bootNodeAddress: "/dns4/cloudagent-veritable-cloudagent-0-swarm.alice.svc.cluster.local/tcp/4001/p2p/12D3KooWJsqkYm6JcYCnZxijaN9L1xMLYgD9JbZfC6Rt42omnUfb"
