label: Charlie veritable-cloudagent REST API
endpoint: "http://cloudagent-veritable-cloudagent.charlie.svc.cluster.local:5002"
logLevel: trace
ingress:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: charlie
ipfs:
  persistence:
    size: 5Gi
    storageClass: managed-csi-premium