---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: alice
spec:
  install:
    remediation:
      retries: -1
  releaseName: ui
  chart:
    spec:
      version: 1.0.4
      chart: veritable-ui
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  interval: 10m0s
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: alice-values
      valuesKey: ui-values.yaml
    - kind: Secret
      name: alice-companies-house-api
      valuesKey: key
      targetPath: companiesHouseApiKey.secret
    - kind: Secret
      name: alice-cookie-session-key
      valuesKey: key
      targetPath: cookieSessionKeys.secret[0]
    - kind: Secret
      name: alice-invitation-pin
      valuesKey: pin
      targetPath: invitationPin.secret