label: Alice Veritable UI
publicUrl: "https://alice.vrtbl.com"
apiSwaggerTitle: Alice
apiSwaggerBgColor: "#38b6ff"
idpClientId: "alice"
idpPublicURLPrefix: https://auth.vrtbl.com/realms/alice/protocol/openid-connect
idpInternalURLPrefix: http://keycloak.keycloak.svc.cluster.local/realms/alice/protocol/openid-connect
externalCloudagent:
  host: "cloudagent-veritable-cloudagent-admin.alice.svc.cluster.local"
  port: "3000"
invitationFromCompanyNumber: "07964699"
demoMode: true
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
# Bitnami Legacy images
postgresql:
  global:
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/postgres-exporter
    serviceMonitor:
      enabled: true
      namespace: alice
ingress:
  hostname: alice.vrtbl.com
  ingressClassName: nginx-alice
emailTransport: SMTP_EMAIL
smtpHost: smtp.azurecomm.net
smtpPort: 587
emailFromAddress: "alice@vrtbl.com"
smtpSecure: false
smtpCredentials:
  enabled: true
  existingSecret: smtp-credentials
  existingSecretUserKey: smtp_username
  existingSecretPasswordKey: smtp_client_secret
logLevel: trace