apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alice-vrtbl-com
  namespace: alice
spec:
  # Secret names are always required.
  secretName: alice-vrtbl-com-prod-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
     - Digital Catapult
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  usages:
    - server auth
    - client auth
  dnsNames:
    - alice.vrtbl.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
