---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-infra-sync
  namespace: monitoring
spec:
  interval: 10m0s
  path: ./applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-flux-infra
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: env-sync
  namespace: monitoring
spec:
  interval: 10m0s
  path: ./clusters/azure/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-flux-infra
    namespace: flux-system
  postBuild:
    substitute:
      MONITORING_STACK_HOSTNAME: "monitoring.vrtbl.com"
      MONITORING_STACK_URL: "https://monitoring.vrtbl.com"
