---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-infra-sync
  namespace: monitoring
spec:
  dependsOn:
    - name: project-sync
      namespace: monitoring
  interval: 10m0s
  path: ./applications
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-flux-infra
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: env-sync
  namespace: monitoring
spec:
  dependsOn:
    - name: project-sync
      namespace: monitoring
  interval: 10m0s
  path: ./clusters/azure/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring-flux-infra
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: project-sync
  namespace: monitoring
spec:
  interval: 10m0s
  path: ./clusters/veritable-prod/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
