---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 10m0s
  path: ./clusters/veritable-prod/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 1m
