---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-ingress-independent
  namespace: nginx-ingress
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nginx-ingress-independent
subjects:
- kind: ServiceAccount
  name: nginx-ingress-independent
  namespace: nginx-ingress
roleRef:
  kind: ClusterRole
  name: nginx-ingress-operator-nginx-ingress-admin
  apiGroup: rbac.authorization.k8s.io
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - events
      - nodes
      - pods
      - secrets
      - services
    verbs:
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingressclasses
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - update
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
