# https://github.com/bitnami/charts/blob/main/bitnami/nginx-ingress-controller/values.yaml
# Bitnami Legacy image
image:
  repository: bitnamilegacy/nginx-ingress-controller
defaultBackend:
  image:
    repository: bitnamilegacy/nginx
watchIngressWithoutClass: true
resourcesPreset: micro
ingressClassResource:
  default: true
hostNetwork: true
dnsPolicy: ClusterFirstWithHostNet
service:
  type: NodePort
nodeSelector:
  ingress-ready: "true"
  kubernetes.io/os: linux
tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Equal
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
    operator: Equal
containerPorts:
  http: 80
  https: 443
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
