label: Eve Veritable UI
publicUrl: "https://eve.vrtbl.com"
apiSwaggerTitle: Eve
apiSwaggerBgColor: "#5e17eb"
idpClientId: "eve"
idpPublicURLPrefix: https://auth.vrtbl.com/realms/eve/protocol/openid-connect
idpInternalURLPrefix: http://keycloak.keycloak.svc.cluster.local/realms/eve/protocol/openid-connect
externalCloudagent:
  host: "cloudagent-veritable-cloudagent-admin.eve.svc.cluster.local"
  port: "3000"
invitationFromCompanyNumber: "11837978"
demoMode: true
postgresql:
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: eve
ingress:
  hostname: eve.vrtbl.com
  ingressClassName: nginx-eve
emailTransport: SMTP_EMAIL
smtpHost: smtp.azurecomm.net
smtpPort: 587
emailFromAddress: "eve@vrtbl.com"
emailAdminAddress: "eve@vrtbl.com"
smtpSecure: true
smtpCredentials:
  enabled: true
  existingSecret: smtp-credentials
  existingSecretUserKey: smtp_username
  existingSecretPasswordKey: smtp_client_secret