# https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml
# Bitnami Legacy images
global:
  security:
    allowInsecureImages: true
image:
  repository: bitnamilegacy/keycloak
keycloakConfigCli:
  image:
    repository: bitnamilegacy/keycloak-config-cli
production: true
proxy: edge
ingress:
  enabled: true
  ingressClassName: nginx-keycloak
  hostname: auth.vrtbl.com
adminIngress:
  enabled: true
  ingressClassName: nginx-keycloak
  hostname: auth.vrtbl.com
auth:
  adminUser: "admin"
extraEnvVars:
  - name: KC_HOSTNAME_ADMIN_URL
    value: "https://auth.vrtbl.com/"
  - name: KC_HOSTNAME_URL
    value: "https://auth.vrtbl.com/"
  - name: KC_HOSTNAME_DEBUG
    value: "true"
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: keycloak
    relabelings:
      - action: replace
        sourceLabels: [namespace]
        targetLabel: kubernetes_namespace
postgresql:
  enabled: false
externalDatabase:
  host: keycloak-cnpg-rw.keycloak.svc.cluster.local
  port: 5432
  database: keycloak
  user: keycloak
  existingSecret: keycloak-cnpg-creds
  existingSecretPasswordKey: password
