---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: alice-sync
  namespace: alice
spec:
  interval: 1m
  path: ./clusters/kind-cluster/alice
  prune: true
  dependsOn:
    - name: monitoring-sync
      namespace: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bob-sync
  namespace: bob
spec:
  interval: 1m
  path: ./clusters/kind-cluster/bob
  prune: true
  dependsOn:
    - name: monitoring-sync
      namespace: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: charlie-sync
  namespace: charlie
spec:
  interval: 1m
  path: ./clusters/kind-cluster/charlie
  prune: true
  dependsOn:
    - name: monitoring-sync
      namespace: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik-sync
  namespace: kube-system
spec:
  interval: 1m
  path: ./clusters/kind-cluster/traefik
  prune: true
  dependsOn:
    - name: monitoring-sync
      namespace: monitoring
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudnative-pg-sync
  namespace: cloudnative-pg
spec:
  interval: 1m
  path: ./clusters/kind-cluster/cloudnative-pg
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-sync
  namespace: keycloak
spec:
  interval: 1m
  path: ./clusters/kind-cluster/keycloak
  prune: true
  dependsOn:
    - name: cloudnative-pg-sync
      namespace: cloudnative-pg
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-sync
  namespace: cert-manager
spec:
  interval: 1m
  path: ./clusters/kind-cluster/cert-manager/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
