---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: monitoring-flux-infra
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: bug/triage_configmap_order
  url: https://github.com/digicatapult/monitoring-flux-infra.git
