label: Dave veritable-cloudagent REST API
endpoint: "http://cloudagent-veritable-cloudagent.dave.svc.cluster.local:5002"
logLevel: trace
ingress:
  enabled: false
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
# Bitnami Legacy images
postgresql:
  global:
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/postgres-exporter
    serviceMonitor:
      enabled: true
      namespace: dave
externalDatabase:
  create: false
  host: cloudagent-cnpg-rw.dave.svc.cluster.local
  port: 5432
  user: cloudagent
  database: walletId
  existingSecret: dave-cloudagent-cnpg-creds
  existingSecretPasswordKey: password
  existingSecretPostgresPasswordKey: pgpass
ipfs:
  persistence:
    size: 5Gi
    storageClass: managed-csi-premium
  initConfig:
    bootNodeAddress: "/dns4/cloudagent-veritable-cloudagent-0-swarm.alice.svc.cluster.local/tcp/4001/p2p/12D3KooWJsqkYm6JcYCnZxijaN9L1xMLYgD9JbZfC6Rt42omnUfb"
