---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: charlie-veritable-cloudagent-cnpg
  namespace: charlie
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 1
  storage:
    size: 1Gi
