apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  releaseName: keycloak
  chart:
    spec:
      chart: keycloakx
      sourceRef:
        kind: HelmRepository
        name: codecentric
      version: "7.1.4"
  interval: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: keycloak-values
      valuesKey: values.yaml
