nameOverride: "keycloak"
http:
  relativePath: /auth2
proxy:
  enabled: true
  mode: xforwarded
ingress:
  enabled: true
  servicePort: http
  annotations: {
    nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
  }
database:
  vendor: postgres
  hostname: postgresql-cluster-rw.keycloak.svc.cluster.local
  port: 5432
  database: keycloak
  username: keycloak
  password: keycloak
extraEnv: |
  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    value: admin
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    value: admin
  - name: KC_HOSTNAME_ADMIN
    value: "http://localhost:3080/auth2/"
  - name: KC_HOSTNAME
    value: "http://localhost:3080/auth2/"
  - name: KC_HOSTNAME_DEBUG
    value: "true"
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
args:
  - "start-dev"
  - "--import-realm"
  - "--hostname-strict=false"
  - "--verbose"
extraVolumes: |
  - name: realm-volume
    configMap:
      name: keycloak-realms
      namespace: keycloak
extraVolumeMounts: |
  - mountPath: /opt/keycloak/data/import
    name: realm-volume
