# https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml
# Bitnami Legacy image
image:
  repository: bitnamilegacy/keycloak
httpRelativePath: /auth2/
proxyHeaders: xforwarded
ingress:
  enabled: true
  hostname: localhost
postgresql:
  auth:
    password: postgres
extraEnvVars:
  - name: KC_HOSTNAME_ADMIN
    value: "http://localhost:3080/auth2/"
  - name: KC_HOSTNAME
    value: "http://localhost:3080/auth2/"
  - name: KC_HOSTNAME_DEBUG
    value: "true"
extraStartupArgs: "--import-realm"
extraVolumes:
  - name: realm-volume
    configMap:
      name: keycloak-realms
      namespace: keycloak
extraVolumeMounts:
  - mountPath: /opt/bitnami/keycloak/data/import
    name: realm-volume
resourcesPreset: none
logging:
  level: DEBUG
