# https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml
# Bitnami Legacy images
global:
  security:
    allowInsecureImages: true
image:
  repository: bitnamilegacy/keycloak
keycloakConfigCli:
  enabled: false
  image:
    repository: bitnamilegacy/keycloak-config-cli
httpRelativePath: /auth2/
proxyHeaders: xforwarded
ingress:
  enabled: true
  hostname: localhost
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
# Bitnami Legacy images
postgresql:
  global:
    security:
      allowInsecureImages: false
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    enabled: false
    image:
      repository: bitnamilegacy/os-shell
  metrics:
    enabled: false
    image:
      repository: bitnamilegacy/postgres-exporter
  auth:
    password: postgres
extraEnvVars:
  - name: KC_HOSTNAME_ADMIN
    value: "http://localhost:3080/auth2/"
  - name: KC_HOSTNAME
    value: "http://localhost:3080/auth2/"
  - name: KC_HOSTNAME_DEBUG
    value: "true"
extraStartupArgs: "--import-realm"
extraVolumes:
  - name: realm-volume
    configMap:
      name: keycloak-realms
      namespace: keycloak
extraVolumeMounts:
  - mountPath: /opt/bitnami/keycloak/data/import
    name: realm-volume
resourcesPreset: none
logging:
  level: DEBUG
