---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudagent
  namespace: bob
spec:
  install:
    remediation:
      retries: -1
  releaseName: cloudagent
  chart:
    spec:
      version: 2.4.16
      chart: veritable-cloudagent
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  interval: 10m0s
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: bob-values
      valuesKey: cloudagent-values.yaml
    - kind: Secret
      name: bob-wallet-key
      valuesKey: key
      targetPath: walletKey.secret
    - kind: Secret
      name: bob-cloudagent-postgres-creds
      valuesKey: password
      targetPath: postgresql.auth.password
