label: Bob veritable-cloudagent REST API
endpoint: ["http://cloudagent-veritable-cloudagent.bob.svc.cluster.local:5002"]
logLevel: trace
ingress:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: bob
image:
  tag: v0.10.26