label: Bob veritable-cloudagent REST API
endpoint: "http://cloudagent-veritable-cloudagent.bob.svc.cluster.local:5002"
logLevel: trace
ingress:
  enabled: false
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
# Bitnami Legacy images
postgresql:
  global:
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/postgres-exporter
    serviceMonitor:
      enabled: true
      namespace: bob
ipfs:
  persistence:
    size: 5Gi
    storageClass: managed-csi-premium
  initConfig:
    bootNodeAddress: "/dns4/cloudagent-veritable-cloudagent-0-swarm.alice.svc.cluster.local/tcp/4001/p2p/12D3KooWEsHEGsiMuH4qhqYg5VpbZhRz5yaRZr2Uaz4Cywid9BMo"
