---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: chore/verify_monitoring_stack_project_overlay
  url: https://github.com/digicatapult/veritable-flux-infra.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/kind-cluster/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
