apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alice
resources:
  - source.yaml
  - veritable-cloudagent
  - veritable-ui
configMapGenerator:
  - name: alice-values
    files:
      - values-veritable-cloudagent.yaml=veritable-cloudagent/values.yaml
      - values-veritable-ui.yaml=veritable-ui/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true