---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ui-cnpg
  namespace: bob
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  instances: 2
  storage:
    size: 5Gi
    storageClass: managed-csi-premium
  enableSuperuserAccess: true
  superuserSecret:
    name: bob-ui-cnpg-superuser-creds
  bootstrap:
    initdb:
      database: veritable-ui
      owner: veritable-ui
      secret:
        name: bob-ui-cnpg-creds
      import:
        type: microservice
        databases:
          - veritable-ui
        source:
          externalCluster: ui-vui-postgresql
  externalClusters:
    - name: ui-vui-postgresql
      connectionParameters:
        host: ui-vui-postgresql.bob.svc.cluster.local
        port: "5432"
        user: postgres
        dbname: postgres
      password:
        name: bob-ui-cnpg-superuser-creds
        key: postgres-password
