---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: dave
spec:
  install:
    remediation:
      retries: -1
  releaseName: ui
  chart:
    spec:
      version: 1.0.8
      chart: veritable-ui
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  interval: 10m0s
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: dave-values
      valuesKey: ui-values.yaml
    - kind: Secret
      name: dave-companies-house-api
      valuesKey: key
      targetPath: companysHouseApiKey.secret
    - kind: Secret
      name: dave-cookie-session-key
      valuesKey: key
      targetPath: cookieSessionKeys.secret
    - kind: Secret
      name: dave-invitation-pin
      valuesKey: pin
      targetPath: invitationPin.secret
    - kind: Secret
      name: dave-auth-client-secret
      valuesKey: secret
      targetPath: idpClientSecret