label: Dave Veritable UI
publicUrl: "https://dave.vrtbl.com"
apiSwaggerTitle: Dave
apiSwaggerBgColor: "#00bf63"
idpClientId: "dave"
idpPublicURLPrefix: https://auth.vrtbl.com/realms/dave/protocol/openid-connect
idpInternalURLPrefix: http://keycloak-http.keycloak.svc.cluster.local/realms/dave/protocol/openid-connect
externalCloudagent:
  host: "cloudagent-veritable-cloudagent-admin.dave.svc.cluster.local"
  port: "3000"
invitationFromCompanyNumber: "08705784"
demoMode: true
postgresql:
  enabled: false
externalDatabase:
  create: false
  host: ui-cnpg-rw.dave.svc.cluster.local
  port: 5432
  user: veritable-ui
  database: veritable-ui
  existingSecret: dave-ui-cnpg-creds
  existingSecretPasswordKey: password
  existingSecretPostgresPasswordKey: pgpass
ingress:
  hostname: dave.vrtbl.com
  ingressClassName: nginx-dave
emailTransport: SMTP_EMAIL
smtpHost: smtp.azurecomm.net
smtpPort: 587
emailFromAddress: "dave@vrtbl.com"
smtpSecure: false
smtpCredentials:
  enabled: true
  existingSecret: smtp-credentials
  existingSecretUserKey: smtp_username
  existingSecretPasswordKey: smtp_client_secret
openCorporatesApiUrl: "https://api.opencorporates.com/v0.4"
openCorporatesApiKey:
  enabled: false
  existingSecret: opencorporates-api-key
  existingSecretKey: key
ipidApiUrl: "https://sandbox.ipid.works"
ipidCustomerId: "digicatapult-uat"
ipidApiKey:
  enabled: false
  existingSecret: ipid-api-key
  existingSecretKey: key