label: Dave Veritable UI
publicUrl: "https://dave.vrtbl.com"
apiSwaggerTitle: Dave
apiSwaggerBgColor: "#00bf63"
idpClientId: "dave"
idpPublicURLPrefix: https://auth.vrtbl.com/realms/dave/protocol/openid-connect
idpInternalURLPrefix: http://keycloak.keycloak.svc.cluster.local/realms/dave/protocol/openid-connect
externalCloudagent:
  host: "cloudagent-veritable-cloudagent-admin.dave.svc.cluster.local"
  port: "3000"
invitationFromCompanyNumber: "08705784"
demoMode: true
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
# Bitnami Legacy images
postgresql:
  global:
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/postgres-exporter
    serviceMonitor:
      enabled: true
      namespace: dave
ingress:
  hostname: dave.vrtbl.com
  ingressClassName: nginx-dave
emailTransport: SMTP_EMAIL
smtpHost: smtp.azurecomm.net
smtpPort: 587
emailFromAddress: "dave@vrtbl.com"
smtpSecure: false
smtpCredentials:
  enabled: true
  existingSecret: smtp-credentials
  existingSecretUserKey: smtp_username
  existingSecretPasswordKey: smtp_client_secret
openCorporatesApiUrl: "https://api.opencorporates.com/v0.4"
openCorporatesApiKey:
  enabled: true
  existingSecret: opencorporates-api-key
  existingSecretKey: key
ipidApiUrl: "https://sandbox.ipid.works"
ipidCustomerId: "digicatapult-uat"
ipidApiKey:
  enabled: true
  existingSecret: ipid-api-key
  existingSecretKey: key