apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - release.yaml
  - source.yaml
configMapGenerator:
  - name: flux-operator-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
