---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 10m
  url: oci://quay.io/fluxoperatordev/charts
  type: oci
