---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: dave
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  releaseName: ingress-nginx
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
      version: "4.13.2"
  interval: 10m
  # Default values
  # https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: dave-values
      valuesKey: nginx-values.yaml
