---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: alice-veritable-cloudagent
  namespace: alice
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      chart: veritable-cloudagent
      sourceRef:
        kind: HelmRepository
        name: digicatapult
      version: 3.0.3
  valuesFrom:
  - kind: ConfigMap
    name: alice-values
    valuesKey: values-veritable-cloudagent.yaml
  interval: 10m0s
