apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: ghcr.io/fluxcd
  components:
    - source-controller
    - kustomize-controller
    - helm-controller
    - notification-controller
  cluster:
    type: kubernetes
    networkPolicy: true
    domain: cluster.local
  sync:
    kind: GitRepository
    url: https://github.com/digicatapult/veritable-flux-infra.git
    ref: refs/heads/feature/add_flux_operator
    path: clusters/kind-cluster/base
