---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: alice-veritable-ui
  namespace: alice
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  releaseName: ui
  chart:
    spec:
      chart: veritable-ui
      sourceRef:
        kind: HelmRepository
        name: digicatapult
      version: 1.4.45
  interval: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: alice-values
      valuesKey: values-veritable-ui.yaml
