---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bob-veritable-cloudagent-cnpg
  namespace: bob
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 1
  storage:
    size: 1Gi
  enableSuperuserAccess: false
  bootstrap:
    initdb:
      database: wallet-id
      owner: bob
      import:
        type: microservice
        databases:
          - wallet-id
        source:
          externalCluster: bob-veritable-cloudagent-postgresql
  externalClusters:
    - name: bob-veritable-cloudagent-postgresql
      connectionParameters:
        host: bob-veritable-cloudagent-postgresql.bob.svc.cluster.local
        port: "5432"
        user: postgres
        dbname: postgres
      password:
        name: bob-veritable-cloudagent-postgresql
        key: postgres-password
