---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: bob-veritable-cloudagent
  namespace: bob
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      chart: veritable-cloudagent
      sourceRef:
        kind: HelmRepository
        name: digicatapult
      version: 2.4.27
  valuesFrom:
  - kind: ConfigMap
    name: bob-values
    valuesKey: values-veritable-cloudagent.yaml
  interval: 10m0s
