label: "bob veritable-cloudgent REST API"
walletkey:
  secret: bob
logLevel: 2
endpoint: ["http://bob-veritable-cloudagent.bob.svc.cluster.local:5002/"]

ingress:
  enabled: false
postgresql:
  auth:
    password: postgres
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace
