label: "Bob Veritable Cloud Agent REST API"
walletkey:
  secret: bob
logLevel: trace
endpoint: ["http://bob-veritable-cloudagent.bob.svc.cluster.local:5002/"]
ingress:
  enabled: false
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
# Bitnami Legacy images
postgresql:
  # image:
  #   repository: bitnamilegacy/postgresql
  volumePermissions:
    enabled: false
    # image:
    #   repository: bitnamilegacy/os-shell
  auth:
    password: postgres
  metrics:
    # image:
    #   repository: bitnamilegacy/postgres-exporter
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      relabelings:
        - action: replace
          sourceLabels: [namespace]
          targetLabel: kubernetes_namespace
