label: "Bob Veritable Cloud Agent REST API"
walletId: bob
walletkey:
  secret: bob
logLevel: trace
endpoint: ["http://bob-veritable-cloudagent.bob.svc.cluster.local:5002/"]
ingress:
  enabled: false
postgresql:
  enabled: false
externalDatabase:
  create: false
  host: bob-veritable-cloudagent-cnpg-rw.bob.svc.cluster.local
  port: 5432
  user: postgres
  password: postgres
  database: veritable-cloudagent
  postgresPassword: postgres
  postgresqlPostgresPassword: postgres
