---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: postgresql
  namespace: keycloak
spec:
  name: bitnami_keycloak
  owner: bn_keycloak
  cluster:
    name: postgresql
  databaseReclaimPolicy: delete
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: keycloak
  namespace: keycloak
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: postgresql
  databaseReclaimPolicy: delete
