---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ui
  namespace: bob
spec:
  install:
    remediation:
      retries: -1
  releaseName: ui
  chart:
    spec:
      version: 1.1.38
      chart: veritable-ui
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  interval: 10m0s
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: bob-values
      valuesKey: ui-values.yaml
    - kind: Secret
      name: bob-companies-house-api
      valuesKey: key
      targetPath: companysHouseApiKey.secret
    - kind: Secret
      name: bob-cookie-session-key
      valuesKey: key
      targetPath: cookieSessionKeys.secret
    - kind: Secret
      name: bob-invitation-pin
      valuesKey: pin
      targetPath: invitationPin.secret
    - kind: Secret
      name: bob-auth-client-secret
      valuesKey: secret
      targetPath: idpClientSecret
    - kind: Secret
      name: admin-email-address
      valuesKey: address
      targetPath: emailAdminAddress
    - kind: Secret
      name: bob-ui-postgres-creds
      valuesKey: password
      targetPath: postgresql.auth.password
