label: Bob Veritable UI
publicUrl: "https://bob.vrtbl.com"
apiSwaggerTitle: Bob
apiSwaggerBgColor: "#ff3131"
idpClientId: "bob"
idpPublicURLPrefix: https://auth.vrtbl.com/realms/bob/protocol/openid-connect
idpInternalURLPrefix: http://keycloak.keycloak.svc.cluster.local/realms/bob/protocol/openid-connect
externalCloudagent:
  host: "cloudagent-veritable-cloudagent-admin.bob.svc.cluster.local"
  port: "3000"
invitationFromCompanyNumber: "04659351"
demoMode: true
postgresql:
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: bob
ingress:
  hostname: bob.vrtbl.com
  ingressClassName: nginx-bob
emailTransport: SMTP_EMAIL
smtpHost: smtp.azurecomm.net
smtpPort: 587
emailFromAddress: "bob@vrtbl.com"
smtpSecure: false
smtpCredentials:
  enabled: true
  existingSecret: smtp-credentials
  existingSecretUserKey: smtp_username
  existingSecretPasswordKey: smtp_client_secret