---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-cnpg
  namespace: keycloak
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.3
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-cnpg-creds
---
apiVersion: v1
data:
  username: a2V5Y2xvYWs=
  password: a2V5Y2xvYWs=
kind: Secret
metadata:
  name: keycloak-cnpg-creds
  namespace: keycloak
type: kubernetes.io/basic-auth
