---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: keycloak
  namespace: keycloak
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: keycloak-cnpg
  databaseReclaimPolicy: retain
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-cnpg
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 1
  storage:
    size: 1Gi
  managed:
    roles:
    - name: keycloak
      ensure: present
      login: true
      superuser: false
      createdb: true
      createrole: true
      inherit: false
      replication: false
      bypassrls: false
      connectionLimit: 4
      validUntil: "2050-01-01T00:00:00Z"
      inRoles:
        - pg_monitor
        - pg_signal_backend
      passwordSecret:
        name: keycloak-cnpg-creds
---
apiVersion: v1
data:
  username: a2V5Y2xvYWs=
  password: a2V5Y2xvYWs=
kind: Secret
metadata:
  name: keycloak-cnpg-creds
  namespace: keycloak
type: kubernetes.io/basic-auth
