apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
resources:
  - database.yaml
  - release.yaml
configMapGenerator:
  - name: cluster-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
