apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: keycloak
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  releaseName: postgresql
  chart:
    spec:
      chart: cluster
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
      version: "0.3.1"
  interval: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: cluster-values
      valuesKey: values.yaml
