---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager 
  namespace: cert-manager
spec:
  install:
    remediation:
      retries: -1
  releaseName: cert-manager
  chart:
    spec:
      version: 1.18.2
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: cert-manager
  interval: 10m0s
  # Default values
  # https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
      valuesKey: values.yaml
