apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager 
resources:
  - source.yaml
  - release.yaml
  - issuer-sync.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - values-cert-manager.yaml=values.yaml
configurations:
  - kustomization-config.yaml
generatorOptions:
  disableNameSuffixHash: true

