installCRDs: true
metrics:
  enabled: true
  serviceMonitor:
    enabled: false
    namespace: cert-manager
    relabelings:
      - action: replace
        sourceLabels: [namespace]
        targetLabel: kubernetes_namespace