---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudagent
  namespace: eve
spec:
  install:
    remediation:
      retries: -1
  releaseName: cloudagent
  chart:
    spec:
      version: 2.1.0
      chart: veritable-cloudagent
      sourceRef:
        kind: HelmRepository
        name: digicatapult
  interval: 10m0s
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: eve-values
      valuesKey: cloudagent-values.yaml
    - kind: Secret
      name: eve-wallet-key
      valuesKey: key
      targetPath: walletKey.secret
