label: Eve veritable-cloudagent REST API
endpoint: "http://cloudagent-veritable-cloudagent.eve.svc.cluster.local:5002"
logLevel: trace
ingress:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: eve
ipfs:
  persistence:
    size: 5Gi
    storageClass: managed-csi-premium
  initConfig:
    bootNodeAddress: "/dns4/cloudagent-veritable-cloudagent-0-swarm.alice.svc.cluster.local/tcp/4001/p2p/12D3KooWGnmQExB4qMBiVk1LkcEGG4xGpk9vDEpHC444NVAjq1jq"
