apiVersion: v1
data:
    key: ENC[AES256_GCM,data:3uJrj9GDlSKgR2weSZwOFsJNROYmd1JT4o+lAN+R/Lz1/nEF32W6JOwH9TM=,iv:tYsvMZ1xU6K7w06itApEIxXNK/yzS3aGRsCa2C1uuyk=,tag:FsN3dqLGfCbeU6tXdypXNQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: alice-cookie-session-key
    namespace: alice
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-06T12:48:01Z"
    mac: ENC[AES256_GCM,data:IIVbVY3+bbDYSUwqjIU05IvWB7NHuxpQnjuM3bAqDY/dIky3qypy1mPZNtAPLhzdjo5ev0AAnE2g3DCUfMVqRIvDDumHcVN+RFgbjHw6LtbbIXRfdp0tXcjYMQhz0ViREGS2BbKXR/+CIz8s6CGE30c4IAwT9aQ2lXwPfigdwCI=,iv:QQnDdEAsLk2D88gLYHN7KMHUZkXe4li9BX9AP0g4pwE=,tag:Pla3sUD9ytBKa1mBArWs2A==,type:str]
    pgp:
        - created_at: "2024-08-06T12:48:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAL6GSWH7TGVkb82CCo0kTK2OEf6FN1g6gEDg6aWfA4Xkw
            KI8X8cNlPeESa16tzL8/v6uSdrLTcwGbYg/2bDIMpnan1jSSoxeH03ySmTKj7cTx
            1GgBCQIQ8SaS2Vy14D2RoLzf1zA4yMbMnOExe42KYowvFlRcXF9IKFQg4nQDj5zH
            xcBIm1YZdOagEL+xy+qpbBG34SkAXgXdVBXQ8EQspSZQqC1hSdTpKsqzaY9elU3K
            rUy+8UJ+bvPQow==
            =mKh0
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
