apiVersion: v1
data:
    password: ENC[AES256_GCM,data:KQS/hWHVzTaGo/2ILO+bGQ==,iv:rUlPjLdK1r3jsKdUAagnPDbBpTIRDHs6y5xfIgZ/WCw=,tag:YhQrqmw6RnP+diHc9ezEvA==,type:str]
    pgpass: ENC[AES256_GCM,data:eJfukFzXCdhHYZtrK3Ix1Q==,iv:AbR3H5aCC2q0b4TgwzIbCd5PXEr3cIOLR8FfHySzyKs=,tag:RkasGyC+WVqwCBI0wFtq/g==,type:str]
    postgres-password: ENC[AES256_GCM,data:ooiojqRvU+p+hGj+fULL3w==,iv:c7fZuqES6AuKQtFLT526ov7gjgKEwL63FPeVbDT96aA=,tag:tlKa/HywEc4Tvfikm/vMkg==,type:str]
    username: ENC[AES256_GCM,data:lx/IMPRfviQtzQK2,iv:uaY+4OAjdgld2e/6PUhwrer/tHlpZohb37QGNoS21as=,tag:lMMAAXxo2Lb5ozh/QfivTw==,type:str]
kind: Secret
metadata:
    name: alice-ui-cnpg-superuser-creds
    namespace: alice
    labels:
        cnpg.io/reload: "true"
sops:
    lastmodified: "2025-10-10T10:44:08Z"
    mac: ENC[AES256_GCM,data:omghFzWwJt6eMvU8VmoLDRaGM1A8nqRjLaLu5xeHpi2AdOcZMXcr1WRb00cM1Z6V7cJKrPMjj40FqVDfcp6CfhPuCo20JUk6fzRol+ZbHoBBMFGcwEsveL5gu/0HDgxoMiHgI1BjSK/N26dxlj2zJ5XTvcJD79xAATbGJ5P1Qsw=,iv:SGVgVi+ph25xu8Z3ADenEMjE4XnTKowJ6B/Kyv/IWGU=,tag:G7Vpv6X2pzeqoSsdFcXTIw==,type:str]
    pgp:
        - created_at: "2025-10-10T10:44:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAKchUYEYH7Psts+98HuBKK9LeBPnfMJkuGEc/5kF1p0Qw
            0yneUgBX3WnUX+sPL+cVWlx4ZVVANwr5acDzMeCKGURElCdiv+GWpGeqB0F7ee1t
            1GYBCQIQ/oQ5KwtkNxrV14zSf8YkGsJnoT5S3XfFjOawXlpZA9tezPelq9N2nBtH
            53qeCWTNjUlizT2o7ZxkdXGs++tTnQI1wspvvYBgOhbdXIbN0PvEuIfcPPFHTVu3
            fPA34/PZtqc=
            =zQsb
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
