apiVersion: v1
data:
    secret: ENC[AES256_GCM,data:HIJcsndhuB7Gf0jsErSnT5Mk4D1Ou1hm5c8S6lEVudqvfglisxzRPGTQmv8=,iv:YE+FdjkDI82wd6G/H+KHsAe3I70bundaua2W7TFu75A=,tag:QHCsXmYEPf1pWfbhtG+K8w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: alice-auth-client-secret
    namespace: alice
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-08T15:01:21Z"
    mac: ENC[AES256_GCM,data:NQf9hYFB35SVsSijysjhi/gn0klZr4gkS1MpEq+fnU4i0yEhZbBhcw5MgWghLu/yvqCZqpdo94+dVWkpeG/+MhkUidlK0if8q1TG/kAu64KnQp0GsgX17cD1eCWBcco/mP0PXXPOmDDzzBiActdhw6Vptgl2qOYAUpwC3iZph0o=,iv:VmA2lr0PZRPPtzvpvsNvraBkqwZkzvfpUVrT+6/Nn3k=,tag:+l6MK5k3KsEqSpupyNUt/A==,type:str]
    pgp:
        - created_at: "2024-08-08T15:01:21Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAUp73VOgw7bSkrHFPBvO7oN6oFwoSexricixoxSDQX0Yw
            EXwm+g0zT/b7VO3MweCq1Qdoy6t266zx0gq5zyUNbPTCHaAj0XsK+yeD5oro9PA9
            1GgBCQIQMZ3nBIcGp1/tgon6fYKT5Aj99N3ytuu09ctrsS5kCHHBGxLUzOO+xw5f
            ILf9PddYQqn/dyYRJhv8JpI4oI4a2v0FPgKvzQzJnl9wFYZX7UNEn+UHTJxRTGvS
            ShsxhjekUksyXQ==
            =6OQE
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
