apiVersion: v1
data:
    address: ENC[AES256_GCM,data:+q8MF+b8bQWgw7yoWYzV9oD+lpQhmFiFfXB3MRsOPhF30j6Gl/W8bu6IyAAZ63eX,iv:CmAyxznba0GGEsmwGnBuSJ4GI/cTV8/UtAs7cGdSX9s=,tag:f0v4hDNT5P+uz2Q9WnqRZw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: admin-email-address
    namespace: alice
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-14T13:39:17Z"
    mac: ENC[AES256_GCM,data:/IHzk9pdjtg9KumLL8VU02WEyKDhRiUoxlxApFRAO0bKRamwoceN0OHLTJ6wUaJbn3HsJrX1MvjBZBk6Voa3yW+VNCEfrCq15MwonpcwZWw0Rnyz/u1WKemTwvPKv0ebCZO3eVfaSPD+MnucCkNxgyiX4GcbixuxezbZUltBA5Q=,iv:DogDE6dx4vSyJhTBezQDlDziHLeIozuSPgkyhz55nw0=,tag:Fs05+0VN53vHYbKUg1lFKg==,type:str]
    pgp:
        - created_at: "2024-10-14T13:39:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAGrN3VNHe4TYoqFEe8cA9NIcI2i1A5QJ8ISWvptnXQwMw
            BgZhj7Y9QSbpm6vS2aX4dQ6bsqsL+mLLWF0rH0BebHEkEs/rXkshIlA4yUxBHQOu
            1GgBCQIQzhYBrOogZPbvo0xWqxrSZMcBpI+RvL1/9HllDpRhNubfvkPlE8ScA9py
            XrV6ok/zdP7cVB9Ceeve0g60aE/6hvIPD1nKW9P+9Lt5j1y23TKa8jJ+LozWMspr
            7ANr2iD5VKKhyQ==
            =4vZ/
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
