apiVersion: v1
data:
    key: ENC[AES256_GCM,data:A0XF7AtiOhTkl0Lx6vTh60V7vu++hPqo0ysh2QSzffiHeIQ573frudyXp5Y=,iv:ivt+Fp6zKsYmwMr3Cl/DuX5jhbZvgOieCCqJ7kzfTkQ=,tag:ViFjxDXT7Pax6UWk4cDFnQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: alice-wallet-key
    namespace: alice
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-06T12:48:01Z"
    mac: ENC[AES256_GCM,data:0F/hEhWSSVSteU1D38wImONhKsI5gFQZm0kh9gm0d5C4+1wjftIg7KE/BkCtSqEwOlBhDTIXH6NJE1LXIPZi0WcwNiDLSs9bp1ewcVYO8xdSH3CDaOdISDQqd8OkThQ4IiJvCdL/WZ5z9xA5weoNTc5c86/efpKUn2Lv/SsIpHw=,iv:6KnQ4NcHX8zHq7gDcYNO3v+mvPGUSG6EMacwMCHBQ1w=,tag:9AG482r66TsT40OB8TigEg==,type:str]
    pgp:
        - created_at: "2024-08-06T12:48:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdA3sCWX+RY0OqC2I88ubXiuEodp+RGyxZT95qRnHBQRiQw
            7OaQFho8bN4vcYcBHF1cDQRXNTcnkHY0+g41rA/EgAOcqEVRTrtE0/llCanFhOhw
            1GgBCQIQHHFVsuBue3VJDgAEGUITRW+GS+nJnV54oAv7Oi8g7uaTHxznYYF9nQlJ
            01ifi8NNRxqFxPbnPgfjVdtw7KTMj/v3KMLmrvQcSFlTXtJLU22THG8W3CqYt9nX
            uUv3/z4Am6VpoA==
            =++TZ
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
