apiVersion: v1
data:
    password: ENC[AES256_GCM,data:wG316eVt68Hq9bjmJSpbjt6L9P6tWaJf,iv:opeGinQqBDTedcLdWULMLKXqyZ5/36UDBF2SODL82hE=,tag:p+QZ/X98knaLlm9ZpW5Uzw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: alice-ui-postgres-creds
    namespace: alice
sops:
    lastmodified: "2025-07-15T08:41:37Z"
    mac: ENC[AES256_GCM,data:NvyrWhJ/d3J1vstt0K3eDFWNRZtNdaNijarpi8OTzSqw7oMXfV783jdvrA9qUwTiGT3GeQJYeAnZlmaSFg/nlKHtkBJ1W2ZPOAVI7EIKjSV3zGRA0HJyBq71hmVWFRf+48kDdlJPNoo1G9X8AVDsihdq3rm24kfO/tADy07TfEo=,iv:bmpnsCaRhKa2Z4LV6IIODSZQCe7ylD1hvNyKkeczmzE=,tag:ZsWGoxk/fnOoCKl3NLwsFw==,type:str]
    pgp:
        - created_at: "2025-07-15T08:41:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdA1oPOavXlFDw2L9gTbxjcDfmlSNb5vf3iioyGwHaY+1ww
            u2tFEM7XW6kuH3TAt6Qjb7yUW1JA70ByjdIFuqrbuJlGJRKxgDvnQ8K2DFKptycT
            1GgBCQIQNAy6FgqNtPbUdWvG9gUl5X70w/Qt1UlbRWIDE6KxccWOHthCO/0m7aQm
            GOxZ13C8LhJb+tQi+kE3LN47CWY39dgK1uqt/bv7LQAfBMLpfba1OLxcns8vn6Ft
            ePAkC/XhH19eOw==
            =l9SN
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
