apiVersion: v1
data:
    address: ENC[AES256_GCM,data:WhGtkG9iOwT7AwC/vISHoF2majlh9U1y8r+6vAb5CaOF4sA7h1o2M5Gtc9Y=,iv:BZ+NJ010mXO3niyhz1dbDqmBnMQhZ9kkqEOKF4Q10Eo=,tag:hEk/0MhEneIsQ4l7oMfM9w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: admin-email-address
    namespace: bob
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-07T15:44:27Z"
    mac: ENC[AES256_GCM,data:RstGYuMeGuETG5ZM5PUCkdkmV9Jf5+YDrnYsWNb8C6i/oe4R5npgG20OxSi+QUAmPxYM880ILY65OdMpNtzpPyy2ydddVzx2IrJSkaO6qI8FenT9Rarz3OUyCWKaptQHFKN7OBtVpxNC3vbZbJW8GuNNJX73LpWhtkyvCVpGUZo=,iv:wYS2HbEQT4HePBEj66IHP/sW/WMCZT6kxIKP2qIh7Vg=,tag:OvkmZe/5oq5veKkv9YjeZw==,type:str]
    pgp:
        - created_at: "2024-10-07T15:44:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAcg0zw+UJboKIrBIeBR7iCGbHbIwvX3MyDbR91ICHMGcw
            5/yAsiZ+N0107TzStZ9vNHS7Z1DxJuPxVCeNfTgVAKfQGT+5hy0OmfQjyjXxCKWj
            1GgBCQIQ49iKCTiXhIzn0vWviGs+/w/Ca07Bk09749fXOwl3cpg4Cei4cO5JiUaj
            iiJoy38dowbS+Sld2LFVFI8MkE7gNl3q0vXSXrtzG3vNVzUAWE/2gjEapHFdBZas
            TCNXSzOzw0tTwg==
            =yfU8
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
