apiVersion: v1
data:
    key: ENC[AES256_GCM,data:KVGMte0xSn4eo2ESfDywoCEvNwQ4NQtpCyBhgg==,iv:6YrH+rEt1A5FUrSpNH55Zyp05fBZ935DVR77y1JQFV8=,tag:x9chizMKLLj/CW3b/SOwSg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: opencorporates-api-key
    namespace: bob
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-08T11:55:38Z"
    mac: ENC[AES256_GCM,data:RwUL0TCdoxhgdKD7UJcOkYMiQ169mj+cAwD9EpoT2G1TCxFcDeMgjLZWAqYxvrSvbbVrcJ3TQpEhfT1JgzmZtlyNoRTix3CNI6//CoS48MULB2DG8mOZ6/rZg/6DQhi2ZtwD/cEScQ1yYfgUhONCs3ab6eDCxUE3+5pZZEaLZu8=,iv:Zkf6FBN4R/8sXicDHwGylDrw2+fePaezBSIggyym548=,tag:h1sWoIn++CeHE492SK5E8w==,type:str]
    pgp:
        - created_at: "2025-09-08T11:55:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAj+UAEKItTgdKr5xWZkqXa/EXqpWIbZOkKO9SZ2xmCw8w
            yfJNOIUmjAfjqgFZDKiwq96KiHaoK92BMfATeoqCw18+p7Nv8aWifEIiLlOLzpZa
            1GgBCQIQiPaWREYGSKdpD8rnK5YPWSo91gr68EjwyH+yNRlC5+57eBfI8TrnP+9b
            OiWyvZDj31RgqKbzd1vilxdJFXbchoalHKyMpyyb2RF9mJMG7jccrzHJMUBgPhTo
            8TydICn2KTYntg==
            =cTZb
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
