apiVersion: v1
data:
    key: ENC[AES256_GCM,data:SsXv0aoAhDmMM5WuHzDwevd0WnMheiHdXN+vyyMlUMGHDfKbHj9dCEFyf6A=,iv:58g5zO3IneskeTQktA1FzphNCFD+7SbmHzwiRGtvgM8=,tag:MoM8Dy1gNZzYpiMEK6AuhA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: bob-cookie-session-key
    namespace: bob
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-28T12:15:32Z"
    mac: ENC[AES256_GCM,data:j3HRGi6Z+B1kkqzIDhl2yDjTzWGxwnnKTEfZYb+kzWv5bdvAUwRdwKsQ7UYkcA1s/B/LqbdajAINu8J2ADLDrqUMUO1Qk5MB7W6PNpvl4t/AfGQlzPYAr5ocTcakhst9gEHhrb06z1t4fc12/yrNRQjBTJgj6CArPS+8tFh226U=,iv:Bj9Veouk0gTTE802M+7GL2ldN/9aFH+cKMXWA55WGSs=,tag:x2sLWSElNH+/ZdqabDtlDg==,type:str]
    pgp:
        - created_at: "2024-08-28T12:15:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAcRmONbcy68n0qDShq4SPUN1Az5AmmfINJ1vBJyYPW2cw
            9BZmWJyDw5eFm50igiIBJa02Oem2uwxkKp2fxESXiYl4Yb2RO9CLHrGAlR0c7X0I
            1GgBCQIQvUAbq11Na0WThU1ai6IJBW5tyfJ0nMLaU+9aKPHMJGyerZjAZ370L1aY
            7ABnKxMGEB1YQclU2vMvcL5sfD5gic+cagNowlbqeq+0zrdradIWe9hV8iHX45h5
            M0cLBgSh+/0vkw==
            =EZzD
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
