apiVersion: v1
data:
    password: ENC[AES256_GCM,data:fKQeNyH9W4R0Zp4noKoOkQ==,iv:WFIfEtudhASXBr+9FLG3u2op+cq3SlobSlYInnSn6/Y=,tag:TR9mxnnRuYTqQjqDlvrXMA==,type:str]
    pgpass: ENC[AES256_GCM,data:R7VRkxdZA/ystQvgmR5lKg==,iv:udf2dUvSSVfRX6mE/GZUxUwyVbCAJ8vmrMrXJYDbvxE=,tag:CWN2lC0A7i7vz1LBerRm4w==,type:str]
    postgres-password: ENC[AES256_GCM,data:oVGxScY5KATRinR9FZ2yoA==,iv:PsY59aXPL4SZ/TGRNLhtCgppAmviUFFNbtue7dAf2Co=,tag:Wiots7U1+Ag6qLizAlt4DA==,type:str]
    username: ENC[AES256_GCM,data:PGdDXPS03sgxdzvi,iv:5lDAkBw9BtGXcBZ/erSmP9B0PVqCpJjE6iZ5aaHtknk=,tag:BuSCNsPTlYBQHCoUg4fjQw==,type:str]
kind: Secret
metadata:
    name: bob-cloudagent-cnpg-superuser-creds
    namespace: bob
    labels:
        cnpg.io/reload: "true"
sops:
    lastmodified: "2025-10-09T14:14:33Z"
    mac: ENC[AES256_GCM,data:mbn8mKmNZAPQqKx2T6XeY9Z/XYB/0K484JbyIhYMCW0EKSKxIA0kW3hVFRhRZR+CisfVNl5bNZAMckp+EriJouWy12uEJ7evsJAB+YrGRVWJ3xWzYEx9JDBCfeMDdA4AU+fn1v0AE3wOtU8HZDRd7jXfX6o/mdajS8QKTYL0nWo=,iv:Zsno/VHSQoWb+wJO6ut9BvifRme+W0iXbKWbZNBBTCs=,tag:ahtzHx/Tk3VoPZ2bQyyP8w==,type:str]
    pgp:
        - created_at: "2025-10-09T14:14:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAwy9qVTpXJyMcowFjb9mSW49GOnjytMGjcv+Pt+/tQkow
            hGyACcHH/AFrrq/9hD0T5dxL2uzrpnKYcPtlDM9f3h8Qnd1gPrrIGaElER6rbp1L
            1GgBCQIQvrTiThtVm4MCOivJKVPIU4VrwgFH/tLvGdsDolmhYMKS7MP6UiFd6TIV
            E5Yg0BQYmIRwH0QBvk/rV5WksqyDP2CF1gQFoqeaEoqeSo6IYFOZM378iFYa3jr3
            7Mxa8TdOgJ63AA==
            =2cH0
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
