apiVersion: v1
data:
    password: ENC[AES256_GCM,data:EUmQUyPL9fwC9XK1LJmL7A==,iv:12L7wbZNmlbHGRjOcMZf7K8nTfZALCLQ5Jgv4viRr6k=,tag:Iq3XnZfJIdcxYFnMDa+1VQ==,type:str]
    pgpass: ENC[AES256_GCM,data:ekHBE+mEvqNdQvAH9HChiw==,iv:duDM75wWskn6coYNkVKyOGzoH5FRxBmZVUIq+2pIdEQ=,tag:6kK4N9K1rbN54suH8sOyhQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:TPklbA9lsFijrG8rA7lemg==,iv:MiQDUwLglhNwHMBm6m0XfWbnJPYFFusAw4piEFPU2EU=,tag:meWpg+6KfOgDgGYDgKlvFQ==,type:str]
    username: ENC[AES256_GCM,data:ubi32cfYer5fLo696xV5Zw==,iv:FpMv1qhSlRsX2Gnyi4dFpGmgjNclFK7RuqLKQP0+6CM=,tag:caW4AKVyx+QHTu/tvlJh5A==,type:str]
kind: Secret
metadata:
    name: charlie-ui-cnpg-creds
    namespace: charlie
    labels:
        cnpg.io/reload: "true"
sops:
    lastmodified: "2025-10-10T10:44:09Z"
    mac: ENC[AES256_GCM,data:sPMG6jmNx85QQRgUWG+n0LozimHWcBwU+K3LUz3xYqiQew/Skok1pqN+FqT6okiekS8gZkhL7WnTgWZl0KP1/HoVVJFVH9mAI62a1Ns0gKu1OGa47rvjMtYJLlbdt0u734q0+kRT7GU9DV85SxrvvCDLtze1Rhj4+ld5RKmgsCw=,iv:YBbpX+p9D9rLnS5S5oJ9jmI0u8SuYs83j09N4dne6GQ=,tag:KO/+xcaFZN9+warameHkEg==,type:str]
    pgp:
        - created_at: "2025-10-10T10:44:08Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAjJc2lpiO5lRvwIxunLoJP80oxDInER2gaPqHY+5OGX4w
            lloltNNAmaQjPPrVH5ANoWuU5ozPOJBFpidbsgZGmPJwW5rIHQ6VxXBVBX2bfIkt
            1GgBCQIQHc8CMuYbyl90u4K/aQHWmGyABXpzzRqKnaUkhWd+JmRU5Kf4xv7CdT6F
            WZDhTobKx4llk7vHHbeyY4TtuxIUdcHsO/fWX/3q13yRZCY3E2vpTahjPs5FjhCW
            cDVR7YQ2xFOJ/w==
            =TFpW
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
