apiVersion: v1
data:
    pin: ENC[AES256_GCM,data:bCNn0mnvXcVQmifdmGePD/MsT9pG7dvl2m2gygGLNbI+Jl/TDuG1oonxQKo=,iv:+QgQtPvAvOTg/RU7YFuWRR8AZlIGfMfePTDgWzvzzlI=,tag:NoHCBi4c7cjF6Hf/i0k+bQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: charlie-invitation-pin
    namespace: charlie
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-28T12:15:33Z"
    mac: ENC[AES256_GCM,data:Z/1UmpFeETsHve9kOEITH9N42LzlPH+26quhjRXqd6Axa9Ok26HytCTW4jUaOHHRpZ6uzO0e9HTlt0pIQGLRJ1ZC9HRvdCaDYi/cSf4AHkKqOp7tkIqYLWZ4ba8OgBa7ytG5LdXvLzKmEClCg2+Zc+oXfGZ3YYqTDyblcHfOpqw=,iv:wqtFLcv702mIm57xAt3OOikFVgKUoO2H9eNPae+0Ims=,tag:b9pCELBkVUo4QvUdsM6Cjg==,type:str]
    pgp:
        - created_at: "2024-08-28T12:15:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAhIqfq6eXyAHy2r+7AGrcLkt9F1iyZA1lI/fnybvFq0Uw
            eM8q/YBJd+5p0kB9f/FyTbhrkPSBeMaJAlmmeVBO4TklQgkMweVqi9L7AB/XlrMN
            1GgBCQIQaWNdEOt2nxcPmuu3mgRxDjJsJ1emcYcn9nYEtCVL9/EBam2N9MDgOT6B
            thbEsiWPsCU5+ZMMZkNXiAPFCIedakRC/iz6Qmt3sr3tHvCZeopSC9Pbu3pCKO8s
            Aw+lKvThKtFv0A==
            =x1pL
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
