apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Gzbd7lvoGYBa5yVr1QtSjg==,iv:Oc4xXqmD6HT0OxpRQc6+8PMWo5heV1MbF4lFdOZXdMI=,tag:wBeeQhZqnxb4G0EKOm2vsw==,type:str]
    pgpass: ENC[AES256_GCM,data:AzOjPrKPNSCs/QZmZ76CTg==,iv:TYXXGH8Ce4AFiNIb54P52pj9wNmuEKzVo8OAeeAq6aA=,tag:Q7MPZTzWxhiMi0zK6nmPVw==,type:str]
    postgres-password: ENC[AES256_GCM,data:WShVKQdmjsM2drc5C7UFTg==,iv:Rv+/Zei3BKNO4COcE9GYI7Qd9VozsN/f23SCYIz5iBI=,tag:ha6rqZOUHOvQH5W2qfKHqg==,type:str]
    username: ENC[AES256_GCM,data:ULo37Ivg5YAVraXHYk7LiQ==,iv:pRe9sL+8QjQMet/C/sVdBvi+U/tzKD5JS7KeBGVgY6k=,tag:Sj/ab9Ha7SUnp+T6UwzO7g==,type:str]
kind: Secret
metadata:
    name: charlie-cloudagent-cnpg-creds
    namespace: charlie
    labels:
        cnpg.io/reload: "true"
sops:
    lastmodified: "2025-10-09T13:39:25Z"
    mac: ENC[AES256_GCM,data:n6XsPNuyeNIg6O8u2swGjQy/hfQXQvWE/86Ia6LAi/s6XAfwONThovsBgi5nFDNmS1RXWhpRxW1OoKGMtsbtpDXKhLsUR+Glq3cQqiPsQxDWhRC9FbdA6UNNLY0gayb8eSRLd6KknR5jdWEZK05FIHRYeCJ9mvusR0SlW3cYRIs=,iv:19V4WqL01vdHZKxxVLG8l5CSwqMj1w/JDWG9ys1qGCo=,tag:JT1T81cgrByDyt13eyZJkQ==,type:str]
    pgp:
        - created_at: "2025-10-09T13:39:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdACctIgEiCFXogm//UJrEAECwTR9N0UjerEJQlsFhHSEww
            W8RfxoeCKSwYSbo4XQcZuXHYCQBhCuybPl+V73LY1ZoyVtpUv+2mBICxO9skIsnH
            1GgBCQIQZuWS32YmUnzZIOzPBlvUrQn0N7b4mx1jLc/O8MfuF5znHi4CB6JlYu3F
            P3LfgVT5t0tB9uGRoI6HDbmbS1EUWm+nnmWxdsuQu8/lu7TcR4AhIBOPMD3/THUR
            yfPy16py0t3JSg==
            =/fTZ
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
