apiVersion: v1
data:
    key: ENC[AES256_GCM,data:x1EQAl0x2dhuV95VUoDQ5h8CT+9Bwl72fKJ9+edV2/d8ytAk7imE3x3s0JY=,iv:Knrq1wSkYNas7kEVb9GaqjZ99VBbqmDdXe2VxjghOAs=,tag:yNJUMq3fXf4AcF01ZyIpRA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: charlie-wallet-key
    namespace: charlie
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-28T12:15:33Z"
    mac: ENC[AES256_GCM,data:/FH5quhQ/kxD/JNjYuBdN3R73wKNjfTL7itO+TyusjV30OHFwIL4ZLepB5x5ipXf52q6yDrA+oEjVBOmvG2ehpGwqBtIKGjc1Yo+ep+OCJBISBdO8P1FURX59iWYy/1hVtGovUj96+IMcOYH2O1H3aNXTBKNnlZJBBxYWsddMO0=,iv:nlH7lVPmmlxoMIGu8Zl44x1qBn1zSOU5tsoAia2fqPo=,tag:MYDZM3ZicNDxxUHNOZvnvg==,type:str]
    pgp:
        - created_at: "2024-08-28T12:15:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdASsDQzeVZSp97rKJ7NwQKHEnOh6HFU4bi4l0W6cLcLBAw
            AVxhpgQFLTXpUvk2iO06J9dWhMQDMd4nJpggAI3UnmKzGjzJISzlHGRMHM80rLTc
            1GgBCQIQy91NrCVBrayjED34n/zEEGKcVq2/TKbPXljJZX9t018ab6bHlEsXEGsB
            62KiRpU79ETrthCdOt1jFY9VuotU8tJ3vpJ0KaUTN4DPMQ26gwoyIrQR9UkuPIrV
            NoxH/qFGRR+5Rw==
            =y0yx
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
