apiVersion: v1
data:
    secret: ENC[AES256_GCM,data:rpu+k8lA7oC82sTZBIgkI2hFwJcHNZ9VyBbM2MUJDnVslldIVH6cFlFBlSk=,iv:BgbphkleSvdhUg/RitFvuCvjYiALsF1u7yb/hhEr1AM=,tag:PzdKAdFILwEtg+WrBco58Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: charlie-auth-client-secret
    namespace: charlie
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-28T12:15:32Z"
    mac: ENC[AES256_GCM,data:A+qFYGCsO1vLVu6YrFy1IWj8xwnxYOpE+qi0R8ohe97WvNFSsSrj6GCtNihSQYT6a6fRiNGPrRg8LpiGYad7CyzXx58Kf2Kbw1EvKRs5Jgqc6Uwwxv0/ySAOdZ8CYU7vXJ08T3zfjtvE75G0iwdaVay0c+tJWrkIXm/uSOc7alo=,iv:tNYanH9B9mAX5J1aczB6MOdp8BACrCDlptyi0ITyXic=,tag:LFPYo/2lmbHLCRLJBZ2cAA==,type:str]
    pgp:
        - created_at: "2024-08-28T12:15:32Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAbCKVQgs86rZb35cMMXpKVVxKCoX3ek0W8duHJzciIhIw
            2Y0Chc+whBdG6YIfKTJgRX62PbJNOQ2phf/YthN9R2bCc9UAcHqVXBRJp1y5d90b
            1GYBCQIQ5RvEvfxSaxuYPdE/85J8NiE1w9br3fbZyfMtyI2C5Pf0THmEL3ZJdm0u
            3UDuDYULyFAs+C7oLYBIqKXYzlbCH3h7NJW2JoZFhq5J84cxrFWw4/Hnc7zsQ6cQ
            dTpHstRDNtY=
            =TdEo
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
