apiVersion: v1
data:
    address: ENC[AES256_GCM,data:i3+Pu11XelY3H/K2yGcna17hljPlXqmZLkLEyK19mou8OJrP1HqRlxd0XVE=,iv:cAMCa86RLh4PLX3qQRYGgTkmLTsMVaRZ8oarbLD4uWs=,tag:6tWHBouPgXOQpmpLAJ1K6Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: admin-email-address
    namespace: charlie
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-07T15:44:27Z"
    mac: ENC[AES256_GCM,data:M7hHmDMLj1/qgjP4JBh04A4DmxAMnBNR7W0/gPI/397hWxuTBWB3bC/3gGG5N0f8NPwY9e6VEu5h/ZCmqahXfAkDfSAV7i3ykbOtyQoIFJl9C2byj8XFo5Mt2QUBdDvg3JaSupGdN1eJycET3uTlYz34yf9gnp9+Ob44JGMqwmI=,iv:CqygpYYXpT3+WAcHy6TP1TZXH0lUoF4O3CjJi6yYpQA=,tag:4bLH2e9RSE6MWXfuw6/lvg==,type:str]
    pgp:
        - created_at: "2024-10-07T15:44:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdA9yUtHPX1/19Gl5T7JNZrEwqXRYEQP9GTXkdZEsGnGDIw
            7RgUnBuOPUuliegB53p4A08g5OqDrNjXOp4XDN066ne3XoaXd6VoauuqrufQP0YO
            1GgBCQIQV57wkoPpzAQoVy/d9SeyCWP/jL3TtvKFKZOJujI62aBzZfIGNnyom718
            zp+yeUm178Z1iS21cKl4r17gDRVv7ZCUp13YQboVLW2Lk6DPuh8R4LLIWxeM84is
            fu2NrlyWQ5FnrA==
            =H0TZ
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
