apiVersion: v1
data:
    address: ENC[AES256_GCM,data:SZGbqAVTCzWg2jrYU4/GkuYsOEaPgyBEjxNRFnJ5n3tFM4qAJ+l6LyR5DCyvf1VM,iv:RE4LkjML3WVdgkmKbQh5XYsivo81VVurQZvVIdRgJ4U=,tag:kgjkyeuS59Qen3sXi0avbQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: admin-email-address
    namespace: charlie
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-14T13:39:17Z"
    mac: ENC[AES256_GCM,data:VWVUO6Fn+ru9qOBaZ7McbVhutkheS2WAUxWhw8nYjNcWSQ3aO799k9XnJteyjKgN+ojb6h+JeikY9ELnhPvkSYAld0/+eDfbuqgC8oyBAjgFCQWvbMHAmxheDxg5Die+DaQV0M3YNI/7DTXwsAg6dEufQpIHEtJjsfjUEiaFL+Q=,iv:I8BJESkFK41RqPz29rCQRMXG9g6l1x/CZXIdHgqSBXo=,tag:8yXgP2xw/efQECXErOfuUQ==,type:str]
    pgp:
        - created_at: "2024-10-14T13:39:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdA0y4XxMjyoYZCcNO47hwSqX3gp/oJAWCkxcDTTvQfxEAw
            hyJDr8WRufjuxAApkC+h2oJ6+GUJKYmCqGAYm9QIBFq4vtUZz1gJ9/GmFepfH4ku
            1GgBCQIQ7UIKO185FGQU376yEckNWCpMJ9dRGtoz3LK3waQmIC8jeu6p8lM4Swuq
            Xju2feYjiWAWC+bnYNuCVH4+Dacmmi1OhHKQ4bqISwn8MyRhvS62Rtmdr6Hx9QQ8
            VygcYoI5DtsRJw==
            =ikX5
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
