apiVersion: v1
data:
    key: ENC[AES256_GCM,data:Ct7iUQtf1BOcBydSBBnakKBm7sMBYXYydWIPcw==,iv:mjEZnVVmrv3kCKaT+uV6p2j5cFpKmexVQ8FZSvyMFgU=,tag:98L0qH9EHGm0pGlShsVEcA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: opencorporates-api-key
    namespace: dave
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-08T11:55:39Z"
    mac: ENC[AES256_GCM,data:OS3BKCuMGbQNClSNefTMztzkpjlhLHji1wXcCe3pFjebqp1XAWM6sxkHNSJqtKDcMQh6cc96//t3Sddfknc9GNAPPneGw8B10f42ze5xgCq5a7s2Z3J6W1f7OmB07pRRJKKVgWjpbhJPO/kIwkIBbj+WIFhUV/VcMbfAt0bCOrc=,iv:PKfny/qLylzFv3fIt8zF/zEFk8Krk8tJgCZvKLjshb8=,tag:3QCj9N2wVRseWCFvQ1mPLQ==,type:str]
    pgp:
        - created_at: "2025-09-08T11:55:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAR9irnj8AbwJBZAr715alAUMGN2Y2keAKhTtUo6XUDUow
            5zSU6PVXqMMKavFQcminaXxTDhSiGZSREXNMGurSaT39yHRY39uBtCnnNg1+io2U
            1GgBCQIQTOmwLj3FRzOmJvfXg/Za6jmnttfp/DjqHLHZwA1Fm5HvEs7j0CpcUkvZ
            HHSU23bzEJ5+abzvenlM5SU2B7rUC/oaLDet4dlVzG975hdVB/4V3Kj+SEf3vM4J
            2eTPK/DAMFIsiA==
            =U13m
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
