apiVersion: v1
data:
    password: ENC[AES256_GCM,data:jJv4uc4AVA7G2m0PcXQbVs0ey0b/AE82,iv:vUZffTpAthXUiUSkechLawFXXG8mGrqFsj1y0Ghu90I=,tag:bKHvZ9lrY4se1FiPcdwP2w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: dave-cloudagent-postgres-creds
    namespace: dave
sops:
    lastmodified: "2025-07-15T08:41:38Z"
    mac: ENC[AES256_GCM,data:BmpIqcCK98AxEsmHKGFcdsApn79knggCnRY7QVzdMkDotjhzLBt2KCRa03C0OigjDh6yHC9XsIIbT8VTRlNCn5EOMhYO6yvjby3XBtFSe5dytyuJdeDUVDd5sE/8ESuyBLc9XqL6ODR8FH2vBFV9DbvZV02EZ4kpgYyqVuEgn3E=,iv:ZVzC3jb9fQUWbCN75DzR9odzYm9YeKAWsgbjj21EDQM=,tag:UePbiQREgBnv3JYQ2Qw7dQ==,type:str]
    pgp:
        - created_at: "2025-07-15T08:41:38Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAkKB2CxPUwFEmvJW3SCWWxw1Ob+mCMo2Z4usOzyLOzDcw
            u5eJt5H0wm3DxoOsc72idxZgCiKiWbo88lC3HFqzTV4btcxbEyqmzTBHFhvOvJys
            1GgBCQIQoH2Zd7WJDo2k1m1zxAgs2VPr/tnoF8Bp6iP/D5rrEE2B5pxAFZLSmDh8
            JMrR5499tKioF8Ci7sly6NzsU1OsYqvniyeue71coe41txj3UujJPjCXGKNwIAp7
            Y2zbpMzZYvrwNA==
            =toKB
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
