apiVersion: v1
data:
    key: ENC[AES256_GCM,data:Ngjf8Pi/lawApt6A38V4b/AoxX5PfzyXIUW8aYZmP0U+mTu94RmVccIeToNINU0Y9nALp9C2x5wVLQUen0FJFYisN8LkDr35eTh5sDPM8XOH4yN3unRAMg==,iv:dVYod9YFjHi7p/LpACiBEIvhN+OpSFquGzogSTL5WW4=,tag:YktJNPyNnV376ucEIOBrOQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: ipid-api-key
    namespace: dave
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-08T11:55:39Z"
    mac: ENC[AES256_GCM,data:Es9gwxeyEo6fB46NiJcdXO3sQka6yuhpkEjH8wcpIcFajkkm+gRgXUVhczh1W3yX1sNeUf147Hgc5RpREwOQO4LD64XSVJBrBaYza1ytge4BHxX0VfNj5l8QBWAIJSE37zGNAw85kmvba8Qgj7IZil7j5/PB3tFDQVY5M9CpAPc=,iv:sBGrH7yLOIJteC+/ogVfniqv62u6cQsLnQvFkBiUH9U=,tag:iMdwvmxqqZ0PBLiSgQbzug==,type:str]
    pgp:
        - created_at: "2025-09-08T11:55:39Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAwXI53OvliWNiW8az2ctVnVAgwLH1Ss65DfBBSeftyh4w
            ZihIMgE5TtkzDRDglRlDKUPBqkO99lgNClZPxkhumy/UBS2nIsfXtP/R5M2+j4jF
            1GYBCQIQFlAfxyS/M1VhA7AyYX8AOn4J+6/u2HxyMQonxp0bO1/KkTqBFRDQ6euW
            reEeo4B+eSjw29bwHNrE9eqrUBkMWBEJM7CkGWOIF+J71/Su2dbL8/M+r/IA2PXy
            uCOC9iNTgjY=
            =Djev
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
