apiVersion: v1
data:
    key: ENC[AES256_GCM,data:41tOifUchOHiLk9MQ07Ve/R1u0t9Rfa6bG2sV0sJPPMFthmdtv0xYnC+UM0=,iv:au4mTXkTFi3puN3k5pJuksZH28otmpcgyhWlEHyhiL8=,tag:wqfOkgG8WtUWM//4CS2brw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: dave-wallet-key
    namespace: dave
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-28T12:15:33Z"
    mac: ENC[AES256_GCM,data:dpTuHAC2np2CBulZJ2SI/EcMxdUPyAmoEV9wADG851oIbV8ZfKdq3GbtMOfQNFeS+Zt/A4lsMPecQCpcjxPLeRBUKzkXlVgIm7UYswgB8rKZVgSMI3yoF0ZsiqhRtS0NpF5PDCUOcakblsO8kuqd7H4ko7bAGWUml1jhElSrufI=,iv:1gB5Dk8DtfCuuYGuKICHPzayDQKYP8g6jaKDJvt9HGw=,tag:LbNNEbDxCwCRPOwOyqIuBQ==,type:str]
    pgp:
        - created_at: "2024-08-28T12:15:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAueJvIZ/Cl4zTVmOlEONRtfhVmiEpLhnA8N72xbt9lEsw
            r5500j/EoNVKrEXl2sq8gekQw9yhFL9zQCflsF7L+trZTFqfsQPbZaNZ8eeKFs4t
            1GYBCQIQ3JmzQ4j2xOZo8xeXg+1NvwhpCeNIDHwrsGr86lyGmiHvTd73sn8jnrIf
            UKDAIt6Zesi0bqbM/RfwY3YelbdvDiF8uLq0DW9UzSrufOGU0h4TdXWaYD6X6yfZ
            uzdRLUZXQSc=
            =35CE
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
