apiVersion: v1
data:
    address: ENC[AES256_GCM,data:FOtquC7Aq4DP58Z5TieCSOyi0Thh8ttriGAYOaniU+RWJn5qVAYsoyw/k/M=,iv:Peax8635b11cY7xcXqzb0zD5n2JLGylKlDVzXTzr7W4=,tag:d3c+DP3MdYDsY5P57dPqmg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: admin-email-address
    namespace: dave
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-07T15:44:27Z"
    mac: ENC[AES256_GCM,data:RgKboNaBTxF1aA79qlw/XOtkrF6zeCG/AP9A5Ri/IY14qBH/vvfXIBsNQIZhV1secRIUTKsqPu2qJrCWs+7yf9YXTb8ANskH5qauJCdeebgseWk4MVsx4ZwHhWOFGvBlvWSUQrpIdDsCC3TH1+TwydYTJK2bBzmEZ7Mh4xYt1Dc=,iv:9jaXlRyOOCIb1AYm6Yvz2bFA9LZJoR8sBZ5D7J13KTU=,tag:1rf/xLaDNMQKzqdLuLf/nQ==,type:str]
    pgp:
        - created_at: "2024-10-07T15:44:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdABtp7P3y4xldHduPDByHj91NqfQpGf6i+xpLCMS8Bezcw
            QGjuRjnx5n3gaxVR0reD4kj3ZXe1lMBCGvvD08cBI6FnWQ1jsszTfouFMYxfKwgx
            1GgBCQIQGQMmhYKUhwO1DjGtUm9nmadCH7BVMmGp05S9wePQzMQu2rcyKOuq3gp6
            l2d9O2srRxuZEBGHp3XsON2Q4zelBOfZRnWzuvnbmKicNFkQyZHRZ3C+9n0tvZRE
            MlaznHTz8ouzAA==
            =1Fys
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
