apiVersion: v1
data:
    secret: ENC[AES256_GCM,data:3UgyFjz6sTpFAny+P/7qhbIgkvvE05bw13HNYAY3B7HXjynCZpUb8Z/ENrs=,iv:eUL1RWs7sGBPCFBzgTlSjk9CoyQLjlezR9LxAlLsm34=,tag:BN/1SbM4dwnrRxfbBtCXTQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: dave-auth-client-secret
    namespace: dave
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-28T12:15:33Z"
    mac: ENC[AES256_GCM,data:67rMhlUr+Ral/hBq/gfu0B2pa/6SxMKlVbO5aF0gtdEtquVggNu+T/etJRUtQig9kOfWRmYJCGA2KQc7aDVHwEu97zZwTeI7dWIxly4CAZklyGdVUS/mi+Pf5upswwIWATJHdkqIYLc5JmYh9/LwvqIUhKyRSCMgE5WuehmGhpo=,iv:ziAhJCUor+SSaAyTbq/rao7H+9O3fIhosIEblvR9zyc=,tag:0eLqVrYwBCAYxWAD1eXpDg==,type:str]
    pgp:
        - created_at: "2024-08-28T12:15:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAohXrfCEfmUTv496UWZjCVzyNL1M8da/nfk4j4amlH1Yw
            7/ZXooa/ZJAJCfw8EClPJ1WJ82AiStVX5xb3cwzy2K+qyZvzS9zNaFu/KrtA0YKB
            1GYBCQIQjtL7TIi0BwuVhfhGdE5K09RR2Apy1HJE/P+0EUPXAQ0gplh/1uXou9Jh
            lBbXLUCCpNw1+D+RfShxXHkEhhfC7Ac4KnFpTzy8W6IsyFOq75VW2RGju0yBcUWw
            QDNIBVk+dkk=
            =naNf
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
