apiVersion: v1
data:
    password: ENC[AES256_GCM,data:bK9yOO0I2m4oYWmKIxOLyA==,iv:yRt87XRY/72zkayLqO1Jq1xMPmDan2ksKWn3pytx9gg=,tag:UVuLZAnlW5JN6FL2i3Cc2Q==,type:str]
    pgpass: ENC[AES256_GCM,data:bM+7nb2j0pHpWGbtthL+Vg==,iv:0RF2ntmi0wId4lv9s/qhXmS33VHDGHd6j4f8KqxRAa0=,tag:xXtub9fu4IPvYdm3vTGpOQ==,type:str]
    postgres-password: ENC[AES256_GCM,data:/r+983MK7vXQR+EWonN1DQ==,iv:mHeQtmefF6iBjpd9BoxRaV+Aa2FmWCfOyR3ocSDalyQ=,tag:Yyo/rlj+c2eZUt5xvJyr+Q==,type:str]
    username: ENC[AES256_GCM,data:kzJ0Og==,iv:ylCt0JgMpR8OIF+6Oeu6LUUcpPzjWQwz8sZJEqpQdp0=,tag:4T5Er5OcVkyIt8i80MJncA==,type:str]
kind: Secret
metadata:
    name: eve-ui-cnpg-creds
    namespace: eve
    labels:
        cnpg.io/reload: "true"
sops:
    lastmodified: "2025-10-10T09:03:15Z"
    mac: ENC[AES256_GCM,data:49iO35NLwHiHF6bBjQoqibgFV5bDD1YDjjosTA99AeUU9z22XLYXJoxC9Do/nypRDYCsZpMAitLHVQpvXhczJ/jJ3iX8wZGhtExIvo0dRLl1wW87jT9ARDNDfCQYqFpjZHkuuWoi58PLA/ajxO+263//TONXBdeush6EBGtyQ5w=,iv:OSrmKRd3qzNS8DmDQK928uxx/OmC6q0iLuxlLTEslAE=,tag:EfuODs+cXnEzSf4cTdS1IA==,type:str]
    pgp:
        - created_at: "2025-10-10T09:03:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAV6LatvR5pTmchGDI32J3aHw40Cuo3MnZHHs5GH/5a1Qw
            8wIyPpAogvGclvwoNAMA2i1vRAFqvhpSOIR1/zygSUpu09kV2fClN96lBKB4qrkC
            1GgBCQIQqDtG/59k0NDS8llhrKOkRfs8VG5mpkffYp593LMGUXJOx+RQLXEXRL3G
            zDTQ3p6CiYgi0WaiFeYUc3oARzFsiax5ZCwAp5aEDYI8US8doWMy0TbdcbUU/xRT
            vgQQWy/ZCuHfqA==
            =fWvx
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
