apiVersion: v1
data:
    pin: ENC[AES256_GCM,data:SesV1CJ25krx+t4LZaMMjx8MMWPm+A/llu0vHL/E9kWq/AU6keWG5ChECjA=,iv:OSB9KjOoJMKpFuRtt5QtKzH+ODdiFgU+FoPpzpUpKJ0=,tag:KxBQX4qmcvRpGMDnAunIIw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: eve-invitation-pin
    namespace: eve
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-08-28T12:15:33Z"
    mac: ENC[AES256_GCM,data:Mm6LyK54ucPZIfwf7EtRDDyr/7NSTb6PUomPfMfKT/mkbmv+4HaDVwXTIDTqDrwYNRnX+Y5MVrGi2y1kRHD16w5kTYeGSmOxforVqQ8++e+BHGqVu45vgnP9fHoPeoxX3un+5V/P53TAPSKZANl6llSXfabma6ea7j5wNoYoO0g=,iv:JKvLbRlWSD1jGu/FjYl5Ckdi+Jgl+/FiproO1OGUUrM=,tag:AfiTnY9Q9v/GzWV1i0fTQQ==,type:str]
    pgp:
        - created_at: "2024-08-28T12:15:33Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAfA6ph6rGWTIdK5Ao1kAp6LmPy7DyvIjvzqnKAITrJV0w
            xn20GrnmciDgUbMQnq0htROpFcELhs0mAYYTreZldFNO0kJB8U03501n/7kE+VZw
            1GgBCQIQ+e10kAsFQIXpI7/Kf1SQBReEQ76L9Fm9RTrCdVnWcwed1ac4fHPLa7Qv
            RLJna/9QfI2gTJOOKiBtOjBp2AuDK+0i7RMt48k1BFOGkydo+eHCOC2Zb/gDZ8K4
            1ahJwPl1cb6v9Q==
            =a0f6
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
