apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Tbf8f3PMRE4VVC/WFRqvMw==,iv:0vKu9lEpUo0Sn7ypK1h0bAyfznKimnsbdZqMRqlT4rw=,tag:duSuBy+l7gy3k9bSS+G13Q==,type:str]
    pgpass: ENC[AES256_GCM,data:XNJcGdGp8yfB/t3LwbMNug==,iv:GX7/pTocBfGHKYOv3cBKEWTWPX8+ThUhFEJ8Z+ifveY=,tag:eCh23qkCzfAKfg7KA3qNvA==,type:str]
    postgres-password: ENC[AES256_GCM,data:OaySbTFtVhWkP1ubyU4qcw==,iv:VLT7Z9+c/pEJ6Gg0rAwdL8oKkzwYvD7If+jeQmXqATU=,tag:ioOa8PNZGcop68UiyGiCIw==,type:str]
    username: ENC[AES256_GCM,data:VMRCkYfZL8GGJ6H5jKqeBQ==,iv:65Ue1sEIQ6Nq9iyIAsFoAGHawSQvuXV3emOcrita2W8=,tag:31+Efv56k5sZASOCHUDPXQ==,type:str]
kind: Secret
metadata:
    name: eve-ui-cnpg-creds
    namespace: eve
    labels:
        cnpg.io/reload: "true"
sops:
    lastmodified: "2025-10-10T10:36:47Z"
    mac: ENC[AES256_GCM,data:uX2LrBedkIfZvMWnIR+jxO0rzgBvcWJKrojmK4QEmSVv4Yd6cpCTtH07xQm8ynjMkL2R6lfrogLSmoLUMWYOShoZ8Z44c3BIhSTsYpoWoyopZng1SE1p3yb8mhBU8NC8ftWfMlUGu+h3cV91ZYy/Ke24LHZo70s1zWrUYiEkQrs=,iv:/RNDlssb1ie0RGgvYyVoNwYumHQnyBYMqC3iyA/11V8=,tag:aurHSXYhmKOzUUxq0y4Dew==,type:str]
    pgp:
        - created_at: "2025-10-10T10:36:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAvLnOfMFXgKz/BpAcqvyaYqQ2D0gxArvacEhoBhrFd0Yw
            hpnayAyYnXndkUAm7GxMB1GLdcnzMpLWAsXPRJoKRKqM69J5xAytH0Hsw55V8vLu
            1GgBCQIQk8QFsHgEI+jzWe70kREOodGu8tqRKB70Xz67ergJk8xGUDbLftXZQikq
            iSjnaNSyBHHftQxz/0VpPXymnZOq+Fy7d1GK1Ekt1VdQVVaOQlR+GhxBtLJ10CHR
            W+GcJKg/R8Xhtg==
            =vKVZ
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
