apiVersion: v1
data:
    address: ENC[AES256_GCM,data:Yaxx93uOvWPDxg4lKhWPF1wp6Y1KNuLN9EV7+Vv7QCIXyfeKdKoSI8BHAAY=,iv:VBCWETkD9eqhqtNrIAkiFO7EDbCYmF0LbKwcrtUFAbY=,tag:zA042Bj0JW1iAvF6r93UeQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: admin-email-address
    namespace: eve
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-10-07T15:44:27Z"
    mac: ENC[AES256_GCM,data:1NKEJGSQzQGrAf14PMm2o5l+upL73mcTIQ/FdnJ1jdJiEzJRMvc+adMBQ9xGfLvPdtYuONcK86rj+69iW8OH99Hetke6KL5Dg5J9lzgxDbQtBf+RxZUW9waWQE0F+vKmPufTnzLVfLcDUogWgdflZb5qKMtfzMm+RxNp6M5ZHF0=,iv:M2CKiCyvTgYfBbYRJLqLF4lOigSWvcqoQo0/tud3AXs=,tag:b7yPK1vA4nzYayt46TNf7Q==,type:str]
    pgp:
        - created_at: "2024-10-07T15:44:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAqkO+OEW2bMT5oxvnOGhA4RVIFIQoqAxaElEcIT+bXykw
            baXNE8EL4ePW/CDxmIm6rW9sROIoEdEUFQDJHAjMlIl9FEpQz0SfEqvL5izKMB/G
            1GYBCQIQMACdOr9j7zffruTvRYvXFcDyOcWCj/odfeEqbDgcJevbMZXhUiTPj+CD
            ezfyzqeYDuyhbdHCG3NzNH5LKR1ml5VgRgdBoA0BDbaqLWsS4x7cIEgqh3OqtJBM
            ct3KNSk0U/I=
            =WjCv
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
