apiVersion: v1
data:
    password: ENC[AES256_GCM,data:WLelS4yvy0cdzryJ9cuAwvsTM3zvkKg4e1Q27IqniKnP57EryPbB5RWoFWs=,iv:NOKHd2D60FbnVTJKusliFfWZZvVeea9flQ2rcvmxpg0=,tag:+AHkrFY9NGAXKdZMRmxKXQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: keycloak-postgres-password
    namespace: keycloak
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-12T14:42:28Z"
    mac: ENC[AES256_GCM,data:mWUfN6zpl+tPxYJG0vfvfLE6pZkigcp18TzJAtOl7vYtVGAwNl8H/UpoFYknu2ZSs4lzyuoBJ+9IuYwNDa7O+bnFvyQSsGZlTSt0QoognG3sqVsS31H7zILM3hP6fpk3GbKVidLyOymMm5W3laSe3ej7Sfucctuz9Rffpi19zsk=,iv:sX3niUq1eu4B0R9RHo3xSDs6Hj37drgftPP88SIq6Qg=,tag:2YoL9WzXBYd2EJ5V0Qle7g==,type:str]
    pgp:
        - created_at: "2024-07-12T14:42:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAsx6YyaBtD+8RnlIAg7H7HlwWSVC9IGrPvA0puOuuMWww
            eFo+D27SAT/PTlHkilry/RWqWvAWaKcjTVUYvkpgfC/fC4LTqHRdlN1ZQdSmrRKK
            1GgBCQIQaFZh/jYntWi9CtbilNYRGIMSFPtFTK3IiALc4t7KBnimQAn0quRUeUGq
            pX+/y+sOSRi0YWHOO96l/wetz3pBy92cFm2OQCRYimbP/uZ+581O38uM69+2nSWe
            Eqzhle37N6RE3g==
            =tttZ
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
