apiVersion: v1
data:
    password: ENC[AES256_GCM,data:EGsjqqLNVRq4dF5V+FzKyA==,iv:DfgVfBS0C+At9nA5ovcuAlemX842OHE7BHHbpOP3F1U=,tag:zUoG2BJY7fPRN++49f1LWw==,type:str]
    username: ENC[AES256_GCM,data:mBCuMDked7pO4XKd,iv:NJZKkQDimpV2gchnQCeK3XCBfIR9iy150q6QP5PEYZY=,tag:77TXa8NsLUEyo7iUKWkv+g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: keycloak-external-creds
    namespace: keycloak
    labels:
        cnpg.io/reload: "true"
sops:
    lastmodified: "2025-09-24T09:03:01Z"
    mac: ENC[AES256_GCM,data:v/KfYuNLLerOOiyFd62KU3ylKZCXb9pyGp7+HdAWqnc8Dn9oAroUubYEATOKq+/bTWcEYmAKVJ5pxA8K9RuJtcmql7ZDeid6/1ODGyvzGJloCXRx/DC7q90LGsAOdDJE73Zuh6qKQf3OZTJJ+4LSKis8GI9VBcoQYNQIFkpiBm0=,iv:wxvqC5QCcUt0HBLKtciXc6d6GkXHoYvd3YKLuTn71Qc=,tag:tFNIr1XTZyaeMbmH0AaNgA==,type:str]
    pgp:
        - created_at: "2025-09-24T09:03:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4Dnkn8tt10QEQSAQdAS5K1wy0Ol12ZEM9cuwVPKrBYGhiY/7Ov5ze92/GtQB0w
            GjUjYbfpwPCZFxXW/OU5uTvMHhbHa6dFE0wyGLJiXtxErFV85gFSphR0uHs1rxuG
            1GgBCQIQEd+9d3FiSGjBk5pYMY7QJuL9p+ZFYdTMRQ2l+vb5XVd0ugEN/bVB+CqK
            Kwn78RgE0vakvL6NH740vU6AfBg067hbK/zSMwYor1und6CanmnDoLxB2lcEpWsF
            jKIgXutZEbO8tw==
            =44VH
            -----END PGP MESSAGE-----
          fp: 4A6351B3CE46129AA516AF77DAF4C53DA4A9B16C
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
