---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: charlie-veritable-cloudagent
  namespace: charlie
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  chart:
    spec:
      chart: veritable-cloudagent
      sourceRef:
        kind: HelmRepository
        name: digicatapult
      version: 3.0.50
  valuesFrom:
  - kind: ConfigMap
    name: charlie-values
    valuesKey: values-veritable-cloudagent.yaml
  interval: 10m0s
