label: "Charlie Veritable Cloud Agent REST API"
walletkey:
  secret: charlie
logLevel: trace
endpoint: ["http://charlie-veritable-cloudagent.bob.svc.cluster.local:5002/"]
ingress:
  enabled: false
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
# Bitnami Legacy images
postgresql:
  enabled: false
externalDatabase:
  host: charlie-veritable-cloudagent-cnpg-rw.keycloak.svc.cluster.local
  port: 5432
  user: veritable-cloudagent
  password: veritable-cloudagent
  database: walletId
  create: false
  postgresqlPostgresUser: postgres
  postgresqlPostgresPassword: postgres
