label: "Charlie Veritable Cloud Agent REST API"
walletId: wallet_id
walletkey:
  secret: charlie
logLevel: trace
endpoint: ["http://charlie-veritable-cloudagent.bob.svc.cluster.local:5002/"]
ingress:
  enabled: false
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
# Bitnami Legacy images
postgresql:
  enabled: false
externalDatabase:
  host: charlie-veritable-cloudagent-cnpg-rw.charlie.svc.cluster.local
  port: 5432
  user: veritable_cloudagent
  password: veritable_cloudagent
  database: wallet_id
  create: true
  existingSecret: charlie-veritable-cloudagent-cnpg-creds
  postgresqlPostgresUser: postgres
  postgresqlPostgresPassword: postgres
