label: Alice veritable-cloudagent REST API
endpoint: "http://cloudagent-veritable-cloudagent.alice.svc.cluster.local:5002"
logLevel: trace
ingress:
  enabled: false
postgresql:
  enabled: false
externalDatabase:
  create: false
  host: cloudagent-cnpg-rw.alice.svc.cluster.local
  port: 5432
  user: cloudagent
  database: walletId
  existingSecret: alice-cloudagent-cnpg-creds
  existingSecretPasswordKey: password
  existingSecretPostgresPasswordKey: pgpass
ipfs:
  persistence:
    size: 5Gi
    storageClass: managed-csi-premium