label: Alice veritable-cloudagent REST API
endpoint: "http://cloudagent-veritable-cloudagent.alice.svc.cluster.local:5002"
logLevel: trace
ingress:
  enabled: false
postgresql:
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      namespace: alice
image:
  tag: v0.10.26