label: Alice veritable-cloudagent REST API
endpoint: "http://cloudagent-veritable-cloudagent.alice.svc.cluster.local:5002"
logLevel: trace
ingress:
  enabled: false
# https://github.com/bitnami/charts/blob/main/bitnami/postgresql/values.yaml
# Bitnami Legacy images
postgresql:
  global:
    security:
      allowInsecureImages: true
  image:
    repository: bitnamilegacy/postgresql
  volumePermissions:
    image:
      repository: bitnamilegacy/os-shell
  primary:
    persistence:
      storageClass: managed-csi-premium
      size: 5Gi
  metrics:
    enabled: true
    image:
      repository: bitnamilegacy/postgres-exporter
    serviceMonitor:
      enabled: true
      namespace: alice
ipfs:
  persistence:
    size: 5Gi
    storageClass: managed-csi-premium