---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: bob
spec:
  install:
    remediation:
      retries: -1
  releaseName: nginx-ingress-controller
  chart:
    spec:
      version: 11.6.27
      chart: nginx-ingress-controller
      sourceRef:
        kind: HelmRepository
        name: bitnami-oci
  interval: 10m0s
  # Default values
  # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
  valuesFrom:
    - kind: ConfigMap
      name: bob-values
      valuesKey: nginx-values.yaml
