# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
grafana:
  env:
    JAEGER_AGENT_PORT: ""
  envValueFrom:
    KEYCLOAK_CLIENT_SECRET:
      secretKeyRef:
        name: grafana-client-secret
        key: grafana-client-secret
  grafana.ini:
    server:
      root_url: https://monitoring.vrtbl.com
    auth.generic_oauth:
      enabled: true
      name: Keycloak
      allow_sign_up: true
      scopes: openid,email,profile,offline_access,roles
      auth_url: https://auth.vrtbl.com/realms/idp-broker/protocol/openid-connect/auth
      token_url: https://auth.vrtbl.com/realms/idp-broker/protocol/openid-connect/token
      api_url: https://auth.vrtbl.com/realms/idp-broker/protocol/openid-connect/userinfo
      client_id: grafana
      client_secret: "${KEYCLOAK_CLIENT_SECRET}"
      role_attribute_path: contains(groups[*], 'grafana_admins') && 'Admin' || contains(groups[*], 'grafana_users') && 'Viewer'
      use_pkce: true
      use_refresh_token: true
  ingress:
    enabled: true
    hosts:
      - monitoring.vrtbl.com
    ingressClassName: nginx-monitoring
