apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: charlie
resources:
  - cloudagent
  - nginx
  - ui
  - source.yaml
configMapGenerator:
  - name: charlie-values
    files:
      - cloudagent-values.yaml=cloudagent/values.yaml
      - nginx-values.yaml=nginx/values.yaml
      - ui-values.yaml=ui/values.yaml
configurations:
  - kustomize-config.yaml
generatorOptions:
  disableNameSuffixHash: true
